# Generated by Django 6.0.4 on 2026-04-25 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_status', models.CharField(default='Pending', max_length=50)),
                ('payment_method', models.CharField(default='Paytm', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.appointment')),
            ],
        ),
    ]
